// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: pb_model.proto

//对应 pocketbase 表： book_info

package book

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Group_ShowType int32

const (
	Group_OneColumn Group_ShowType = 0
	Group_TwoColumn Group_ShowType = 1
)

// Enum value maps for Group_ShowType.
var (
	Group_ShowType_name = map[int32]string{
		0: "OneColumn",
		1: "TwoColumn",
	}
	Group_ShowType_value = map[string]int32{
		"OneColumn": 0,
		"TwoColumn": 1,
	}
)

func (x Group_ShowType) Enum() *Group_ShowType {
	p := new(Group_ShowType)
	*p = x
	return p
}

func (x Group_ShowType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Group_ShowType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_model_proto_enumTypes[0].Descriptor()
}

func (Group_ShowType) Type() protoreflect.EnumType {
	return &file_pb_model_proto_enumTypes[0]
}

func (x Group_ShowType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Group_ShowType.Descriptor instead.
func (Group_ShowType) EnumDescriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{2, 0}
}

type Repo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CdnUrls []string `protobuf:"bytes,2,rep,name=cdnUrls,proto3" json:"cdnUrls,omitempty"`
}

func (x *Repo) Reset() {
	*x = Repo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{0}
}

func (x *Repo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repo) GetCdnUrls() []string {
	if x != nil {
		return x.CdnUrls
	}
	return nil
}

type Basic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ZhName      string `protobuf:"bytes,3,opt,name=zhName,proto3" json:"zhName,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Author      string `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Cover       string `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	Price       uint32 `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Narrator    string `protobuf:"bytes,10,opt,name=narrator,proto3" json:"narrator,omitempty"`
	Publisher   string `protobuf:"bytes,11,opt,name=publisher,proto3" json:"publisher,omitempty"`
	ReleaseDate string `protobuf:"bytes,12,opt,name=releaseDate,proto3" json:"releaseDate,omitempty"` //e.g 2018-01-01
	// 只有音频的时候才有
	DuraionSum uint32 `protobuf:"varint,13,opt,name=duraionSum,proto3" json:"duraionSum,omitempty"`
}

func (x *Basic) Reset() {
	*x = Basic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Basic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Basic) ProtoMessage() {}

func (x *Basic) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Basic.ProtoReflect.Descriptor instead.
func (*Basic) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{1}
}

func (x *Basic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Basic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Basic) GetZhName() string {
	if x != nil {
		return x.ZhName
	}
	return ""
}

func (x *Basic) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Basic) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Basic) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Basic) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Basic) GetNarrator() string {
	if x != nil {
		return x.Narrator
	}
	return ""
}

func (x *Basic) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *Basic) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Basic) GetDuraionSum() uint32 {
	if x != nil {
		return x.DuraionSum
	}
	return 0
}

type Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShowType Group_ShowType `protobuf:"varint,3,opt,name=showType,proto3,enum=book.Group_ShowType" json:"showType,omitempty"`
	Expand   *Group_Expand  `protobuf:"bytes,4,opt,name=expand,proto3" json:"expand,omitempty"`
}

func (x *Group) Reset() {
	*x = Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{2}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetShowType() Group_ShowType {
	if x != nil {
		return x.ShowType
	}
	return Group_OneColumn
}

func (x *Group) GetExpand() *Group_Expand {
	if x != nil {
		return x.Expand
	}
	return nil
}

type ListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage   uint32 `protobuf:"varint,2,opt,name=perPage,proto3" json:"perPage,omitempty"`
	Sort      string `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Filter    string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Expand    string `protobuf:"bytes,5,opt,name=expand,proto3" json:"expand,omitempty"`
	Fields    string `protobuf:"bytes,6,opt,name=fields,proto3" json:"fields,omitempty"`
	SkipTotal string `protobuf:"bytes,7,opt,name=skipTotal,proto3" json:"skipTotal,omitempty"`
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{3}
}

func (x *ListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReq) GetPerPage() uint32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListReq) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListReq) GetExpand() string {
	if x != nil {
		return x.Expand
	}
	return ""
}

func (x *ListReq) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

func (x *ListReq) GetSkipTotal() string {
	if x != nil {
		return x.SkipTotal
	}
	return ""
}

type ItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expand string `protobuf:"bytes,1,opt,name=expand,proto3" json:"expand,omitempty"`
	Fields string `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ItemReq) Reset() {
	*x = ItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemReq) ProtoMessage() {}

func (x *ItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemReq.ProtoReflect.Descriptor instead.
func (*ItemReq) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{4}
}

func (x *ItemReq) GetExpand() string {
	if x != nil {
		return x.Expand
	}
	return ""
}

func (x *ItemReq) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

type RepoListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Repo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *RepoListResp) Reset() {
	*x = RepoListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepoListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoListResp) ProtoMessage() {}

func (x *RepoListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoListResp.ProtoReflect.Descriptor instead.
func (*RepoListResp) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{5}
}

func (x *RepoListResp) GetItems() []*Repo {
	if x != nil {
		return x.Items
	}
	return nil
}

type GroupListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items      []*Group `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page       uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage    uint32   `protobuf:"varint,3,opt,name=perPage,proto3" json:"perPage,omitempty"`
	TotalItems uint32   `protobuf:"varint,4,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	TotalPages uint32   `protobuf:"varint,5,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
}

func (x *GroupListResp) Reset() {
	*x = GroupListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListResp) ProtoMessage() {}

func (x *GroupListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListResp.ProtoReflect.Descriptor instead.
func (*GroupListResp) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{6}
}

func (x *GroupListResp) GetItems() []*Group {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GroupListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GroupListResp) GetPerPage() uint32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GroupListResp) GetTotalItems() uint32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *GroupListResp) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type BookListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items      []*Basic `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page       uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage    uint32   `protobuf:"varint,3,opt,name=perPage,proto3" json:"perPage,omitempty"`
	TotalItems uint32   `protobuf:"varint,4,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	TotalPages uint32   `protobuf:"varint,5,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
}

func (x *BookListResp) Reset() {
	*x = BookListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookListResp) ProtoMessage() {}

func (x *BookListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookListResp.ProtoReflect.Descriptor instead.
func (*BookListResp) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{7}
}

func (x *BookListResp) GetItems() []*Basic {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BookListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BookListResp) GetPerPage() uint32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *BookListResp) GetTotalItems() uint32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *BookListResp) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// 对应 pocketbase 表 book_info
type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OssHash      string `protobuf:"bytes,1,opt,name=ossHash,proto3" json:"ossHash,omitempty"`
	OssHashTrail string `protobuf:"bytes,2,opt,name=ossHashTrail,proto3" json:"ossHashTrail,omitempty"`
	// 所有资源的总大小(包含音、图)
	AssetsSize uint32 `protobuf:"varint,3,opt,name=assetsSize,proto3" json:"assetsSize,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{8}
}

func (x *FileInfo) GetOssHash() string {
	if x != nil {
		return x.OssHash
	}
	return ""
}

func (x *FileInfo) GetOssHashTrail() string {
	if x != nil {
		return x.OssHashTrail
	}
	return ""
}

func (x *FileInfo) GetAssetsSize() uint32 {
	if x != nil {
		return x.AssetsSize
	}
	return 0
}

type Model struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 基本信息，可从列表 api 中获取
	BasicInfo      *Basic            `protobuf:"bytes,1,opt,name=basicInfo,proto3" json:"basicInfo,omitempty"`
	FileInfo       *FileInfo         `protobuf:"bytes,2,opt,name=fileInfo,proto3" json:"fileInfo,omitempty"`
	Toc            []*Model_Toc      `protobuf:"bytes,3,rep,name=toc,proto3" json:"toc,omitempty"`
	Pages          []*Model_Page     `protobuf:"bytes,4,rep,name=pages,proto3" json:"pages,omitempty"`
	AdditionalInfo map[string]string `protobuf:"bytes,11,rep,name=additionalInfo,proto3" json:"additionalInfo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Model) Reset() {
	*x = Model{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{9}
}

func (x *Model) GetBasicInfo() *Basic {
	if x != nil {
		return x.BasicInfo
	}
	return nil
}

func (x *Model) GetFileInfo() *FileInfo {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

func (x *Model) GetToc() []*Model_Toc {
	if x != nil {
		return x.Toc
	}
	return nil
}

func (x *Model) GetPages() []*Model_Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *Model) GetAdditionalInfo() map[string]string {
	if x != nil {
		return x.AdditionalInfo
	}
	return nil
}

type Group_Expand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books []*Basic `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
}

func (x *Group_Expand) Reset() {
	*x = Group_Expand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Group_Expand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group_Expand) ProtoMessage() {}

func (x *Group_Expand) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group_Expand.ProtoReflect.Descriptor instead.
func (*Group_Expand) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Group_Expand) GetBooks() []*Basic {
	if x != nil {
		return x.Books
	}
	return nil
}

type Model_Toc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 所在的页码
	PageIndex uint32 `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	// 有多少页,默认为1
	PageLength uint32 `protobuf:"varint,2,opt,name=pageLength,proto3" json:"pageLength,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 孩子节点
	Children []*Model_Toc `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *Model_Toc) Reset() {
	*x = Model_Toc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model_Toc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model_Toc) ProtoMessage() {}

func (x *Model_Toc) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model_Toc.ProtoReflect.Descriptor instead.
func (*Model_Toc) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{9, 1}
}

func (x *Model_Toc) GetPageIndex() uint32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *Model_Toc) GetPageLength() uint32 {
	if x != nil {
		return x.PageLength
	}
	return 0
}

func (x *Model_Toc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model_Toc) GetChildren() []*Model_Toc {
	if x != nil {
		return x.Children
	}
	return nil
}

type Model_Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 主要内容的地址
	// 图片点读书: src="xx.jpg"，attr=[ImageAttr]
	// tingyue : src="xx.mp3",attr=[AudioAttr]
	// html    : src="xx.html",attr=[HtmlAudioAttr]
	Src  string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Attr string `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
}

func (x *Model_Page) Reset() {
	*x = Model_Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model_Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model_Page) ProtoMessage() {}

func (x *Model_Page) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model_Page.ProtoReflect.Descriptor instead.
func (*Model_Page) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{9, 2}
}

func (x *Model_Page) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Model_Page) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

// for english book
type Model_Page_RectAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Model_Page_RectAttr_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Model_Page_RectAttr) Reset() {
	*x = Model_Page_RectAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model_Page_RectAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model_Page_RectAttr) ProtoMessage() {}

func (x *Model_Page_RectAttr) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model_Page_RectAttr.ProtoReflect.Descriptor instead.
func (*Model_Page_RectAttr) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{9, 2, 0}
}

func (x *Model_Page_RectAttr) GetItems() []*Model_Page_RectAttr_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// for tingyue
type Model_Page_AudioAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Whole      string `protobuf:"bytes,1,opt,name=whole,proto3" json:"whole,omitempty"`                             //全文
	TimingAttr string `protobuf:"bytes,2,opt,name=timing_attr,json=timingAttr,proto3" json:"timing_attr,omitempty"` //attr=[AudioTimingAttr]
}

func (x *Model_Page_AudioAttr) Reset() {
	*x = Model_Page_AudioAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model_Page_AudioAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model_Page_AudioAttr) ProtoMessage() {}

func (x *Model_Page_AudioAttr) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model_Page_AudioAttr.ProtoReflect.Descriptor instead.
func (*Model_Page_AudioAttr) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{9, 2, 1}
}

func (x *Model_Page_AudioAttr) GetWhole() string {
	if x != nil {
		return x.Whole
	}
	return ""
}

func (x *Model_Page_AudioAttr) GetTimingAttr() string {
	if x != nil {
		return x.TimingAttr
	}
	return ""
}

type Model_Page_AudioTimingAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timing []*Model_Page_AudioTimingAttr_SRT `protobuf:"bytes,2,rep,name=timing,proto3" json:"timing,omitempty"` //[[340,199,0,9]]
}

func (x *Model_Page_AudioTimingAttr) Reset() {
	*x = Model_Page_AudioTimingAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model_Page_AudioTimingAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model_Page_AudioTimingAttr) ProtoMessage() {}

func (x *Model_Page_AudioTimingAttr) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model_Page_AudioTimingAttr.ProtoReflect.Descriptor instead.
func (*Model_Page_AudioTimingAttr) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{9, 2, 2}
}

func (x *Model_Page_AudioTimingAttr) GetTiming() []*Model_Page_AudioTimingAttr_SRT {
	if x != nil {
		return x.Timing
	}
	return nil
}

// for bible
type Model_Page_HtmlAudioAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Audio  string                             `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	Html   string                             `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"` //html全文
	Timing []*Model_Page_HtmlAudioAttr_TagSRT `protobuf:"bytes,3,rep,name=timing,proto3" json:"timing,omitempty"`
}

func (x *Model_Page_HtmlAudioAttr) Reset() {
	*x = Model_Page_HtmlAudioAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model_Page_HtmlAudioAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model_Page_HtmlAudioAttr) ProtoMessage() {}

func (x *Model_Page_HtmlAudioAttr) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model_Page_HtmlAudioAttr.ProtoReflect.Descriptor instead.
func (*Model_Page_HtmlAudioAttr) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{9, 2, 3}
}

func (x *Model_Page_HtmlAudioAttr) GetAudio() string {
	if x != nil {
		return x.Audio
	}
	return ""
}

func (x *Model_Page_HtmlAudioAttr) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *Model_Page_HtmlAudioAttr) GetTiming() []*Model_Page_HtmlAudioAttr_TagSRT {
	if x != nil {
		return x.Timing
	}
	return nil
}

type Model_Page_RectAttr_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rect      *Model_Page_RectAttr_Item_Rect `protobuf:"bytes,1,opt,name=rect,proto3" json:"rect,omitempty"`
	Audio     string                         `protobuf:"bytes,2,opt,name=audio,proto3" json:"audio,omitempty"`
	Text      string                         `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	TextTrans string                         `protobuf:"bytes,4,opt,name=textTrans,proto3" json:"textTrans,omitempty"`
}

func (x *Model_Page_RectAttr_Item) Reset() {
	*x = Model_Page_RectAttr_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model_Page_RectAttr_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model_Page_RectAttr_Item) ProtoMessage() {}

func (x *Model_Page_RectAttr_Item) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model_Page_RectAttr_Item.ProtoReflect.Descriptor instead.
func (*Model_Page_RectAttr_Item) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{9, 2, 0, 0}
}

func (x *Model_Page_RectAttr_Item) GetRect() *Model_Page_RectAttr_Item_Rect {
	if x != nil {
		return x.Rect
	}
	return nil
}

func (x *Model_Page_RectAttr_Item) GetAudio() string {
	if x != nil {
		return x.Audio
	}
	return ""
}

func (x *Model_Page_RectAttr_Item) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Model_Page_RectAttr_Item) GetTextTrans() string {
	if x != nil {
		return x.TextTrans
	}
	return ""
}

type Model_Page_RectAttr_Item_Rect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X      float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y      float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Width  float32 `protobuf:"fixed32,3,opt,name=width,proto3" json:"width,omitempty"`
	Height float32 `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Model_Page_RectAttr_Item_Rect) Reset() {
	*x = Model_Page_RectAttr_Item_Rect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model_Page_RectAttr_Item_Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model_Page_RectAttr_Item_Rect) ProtoMessage() {}

func (x *Model_Page_RectAttr_Item_Rect) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model_Page_RectAttr_Item_Rect.ProtoReflect.Descriptor instead.
func (*Model_Page_RectAttr_Item_Rect) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{9, 2, 0, 0, 0}
}

func (x *Model_Page_RectAttr_Item_Rect) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Model_Page_RectAttr_Item_Rect) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Model_Page_RectAttr_Item_Rect) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Model_Page_RectAttr_Item_Rect) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Model_Page_AudioTimingAttr_SRT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// [340,199,0,9] ms_begin,ms_len,pos_begin,pos_len
	// in seconds
	MsBegin  uint32 `protobuf:"varint,1,opt,name=ms_begin,json=msBegin,proto3" json:"ms_begin,omitempty"`
	MsLen    uint32 `protobuf:"varint,2,opt,name=ms_len,json=msLen,proto3" json:"ms_len,omitempty"`
	PosBegin uint32 `protobuf:"varint,3,opt,name=pos_begin,json=posBegin,proto3" json:"pos_begin,omitempty"`
	PosLen   uint32 `protobuf:"varint,4,opt,name=pos_len,json=posLen,proto3" json:"pos_len,omitempty"`
}

func (x *Model_Page_AudioTimingAttr_SRT) Reset() {
	*x = Model_Page_AudioTimingAttr_SRT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model_Page_AudioTimingAttr_SRT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model_Page_AudioTimingAttr_SRT) ProtoMessage() {}

func (x *Model_Page_AudioTimingAttr_SRT) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model_Page_AudioTimingAttr_SRT.ProtoReflect.Descriptor instead.
func (*Model_Page_AudioTimingAttr_SRT) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{9, 2, 2, 0}
}

func (x *Model_Page_AudioTimingAttr_SRT) GetMsBegin() uint32 {
	if x != nil {
		return x.MsBegin
	}
	return 0
}

func (x *Model_Page_AudioTimingAttr_SRT) GetMsLen() uint32 {
	if x != nil {
		return x.MsLen
	}
	return 0
}

func (x *Model_Page_AudioTimingAttr_SRT) GetPosBegin() uint32 {
	if x != nil {
		return x.PosBegin
	}
	return 0
}

func (x *Model_Page_AudioTimingAttr_SRT) GetPosLen() uint32 {
	if x != nil {
		return x.PosLen
	}
	return 0
}

type Model_Page_HtmlAudioAttr_TagSRT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in seconds
	Start uint32 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End   uint32 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Tag   string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *Model_Page_HtmlAudioAttr_TagSRT) Reset() {
	*x = Model_Page_HtmlAudioAttr_TagSRT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_model_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model_Page_HtmlAudioAttr_TagSRT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model_Page_HtmlAudioAttr_TagSRT) ProtoMessage() {}

func (x *Model_Page_HtmlAudioAttr_TagSRT) ProtoReflect() protoreflect.Message {
	mi := &file_pb_model_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model_Page_HtmlAudioAttr_TagSRT.ProtoReflect.Descriptor instead.
func (*Model_Page_HtmlAudioAttr_TagSRT) Descriptor() ([]byte, []int) {
	return file_pb_model_proto_rawDescGZIP(), []int{9, 2, 3, 0}
}

func (x *Model_Page_HtmlAudioAttr_TagSRT) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Model_Page_HtmlAudioAttr_TagSRT) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Model_Page_HtmlAudioAttr_TagSRT) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

var File_pb_model_proto protoreflect.FileDescriptor

var file_pb_model_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x34, 0x0a, 0x04, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x64, 0x6e, 0x55, 0x72, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x64, 0x6e, 0x55, 0x72, 0x6c, 0x73, 0x22, 0xa5, 0x02, 0x0a,
	0x05, 0x42, 0x61, 0x73, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x7a, 0x68,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x7a, 0x68, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x61, 0x72, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x61, 0x72, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x69, 0x6f, 0x6e, 0x53,
	0x75, 0x6d, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x69, 0x6f,
	0x6e, 0x53, 0x75, 0x6d, 0x22, 0xe0, 0x01, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x77, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x77,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x52, 0x06, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64,
	0x1a, 0x2b, 0x0a, 0x06, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x12, 0x21, 0x0a, 0x05, 0x62, 0x6f,
	0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x22, 0x28, 0x0a,
	0x08, 0x53, 0x68, 0x6f, 0x77, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x6e, 0x65,
	0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x77, 0x6f, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x10, 0x01, 0x22, 0xb1, 0x01, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65,
	0x78, 0x70, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x6b, 0x69, 0x70, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x6b, 0x69, 0x70, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x39, 0x0a, 0x07, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x30, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x52, 0x65, 0x70,
	0x6f, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xa0, 0x01, 0x0a, 0x0d, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x22, 0x9f, 0x01, 0x0a, 0x0c,
	0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x22, 0x68, 0x0a,
	0x08, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x73, 0x73,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x73, 0x73, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x73, 0x73, 0x48, 0x61, 0x73, 0x68, 0x54, 0x72,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x73, 0x73, 0x48, 0x61,
	0x73, 0x68, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xce, 0x09, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x29, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x42, 0x61, 0x73, 0x69,
	0x63, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a, 0x03, 0x74, 0x6f, 0x63, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x54, 0x6f, 0x63, 0x52, 0x03, 0x74, 0x6f, 0x63, 0x12, 0x26, 0x0a, 0x05, 0x70,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x05, 0x70, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x0e, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x61, 0x64,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x41, 0x0a, 0x13,
	0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a,
	0x84, 0x01, 0x0a, 0x03, 0x54, 0x6f, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x63, 0x68, 0x69,
	0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x54, 0x6f, 0x63, 0x52, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x1a, 0x8f, 0x06, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72,
	0x63, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x74, 0x74, 0x72, 0x1a, 0x9c, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x74, 0x41, 0x74,
	0x74, 0x72, 0x12, 0x34, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50,
	0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0xd9, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x37, 0x0a, 0x04, 0x72, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x61, 0x67,
	0x65, 0x2e, 0x52, 0x65, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e,
	0x52, 0x65, 0x63, 0x74, 0x52, 0x04, 0x72, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x75,
	0x64, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x78, 0x74, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x78, 0x74, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x1a, 0x50, 0x0a, 0x04, 0x52, 0x65, 0x63, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x1a, 0x42, 0x0a, 0x09, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x41, 0x74, 0x74,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x68, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x77, 0x68, 0x6f, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x69, 0x6e,
	0x67, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x69,
	0x6d, 0x69, 0x6e, 0x67, 0x41, 0x74, 0x74, 0x72, 0x1a, 0xbe, 0x01, 0x0a, 0x0f, 0x41, 0x75, 0x64,
	0x69, 0x6f, 0x54, 0x69, 0x6d, 0x69, 0x6e, 0x67, 0x41, 0x74, 0x74, 0x72, 0x12, 0x3c, 0x0a, 0x06,
	0x74, 0x69, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x62,
	0x6f, 0x6f, 0x6b, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x2e, 0x41,
	0x75, 0x64, 0x69, 0x6f, 0x54, 0x69, 0x6d, 0x69, 0x6e, 0x67, 0x41, 0x74, 0x74, 0x72, 0x2e, 0x53,
	0x52, 0x54, 0x52, 0x06, 0x74, 0x69, 0x6d, 0x69, 0x6e, 0x67, 0x1a, 0x6d, 0x0a, 0x03, 0x53, 0x52,
	0x54, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x73, 0x5f, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x73, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x15, 0x0a, 0x06,
	0x6d, 0x73, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x73,
	0x4c, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x5f, 0x62, 0x65, 0x67, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x42, 0x65, 0x67, 0x69, 0x6e,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x4c, 0x65, 0x6e, 0x1a, 0xbc, 0x01, 0x0a, 0x0d, 0x48, 0x74,
	0x6d, 0x6c, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x41, 0x74, 0x74, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x75, 0x64, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x75, 0x64, 0x69,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x74, 0x6d, 0x6c, 0x12, 0x3d, 0x0a, 0x06, 0x74, 0x69, 0x6d, 0x69, 0x6e, 0x67, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x2e, 0x48, 0x74, 0x6d, 0x6c, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x41, 0x74, 0x74, 0x72, 0x2e, 0x54, 0x61, 0x67, 0x53, 0x52, 0x54, 0x52, 0x06, 0x74, 0x69,
	0x6d, 0x69, 0x6e, 0x67, 0x1a, 0x42, 0x0a, 0x06, 0x54, 0x61, 0x67, 0x53, 0x52, 0x54, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x42, 0x10, 0x5a, 0x0e, 0x69, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pb_model_proto_rawDescOnce sync.Once
	file_pb_model_proto_rawDescData = file_pb_model_proto_rawDesc
)

func file_pb_model_proto_rawDescGZIP() []byte {
	file_pb_model_proto_rawDescOnce.Do(func() {
		file_pb_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_model_proto_rawDescData)
	})
	return file_pb_model_proto_rawDescData
}

var file_pb_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_model_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pb_model_proto_goTypes = []any{
	(Group_ShowType)(0),                     // 0: book.Group.ShowType
	(*Repo)(nil),                            // 1: book.Repo
	(*Basic)(nil),                           // 2: book.Basic
	(*Group)(nil),                           // 3: book.Group
	(*ListReq)(nil),                         // 4: book.ListReq
	(*ItemReq)(nil),                         // 5: book.ItemReq
	(*RepoListResp)(nil),                    // 6: book.RepoListResp
	(*GroupListResp)(nil),                   // 7: book.GroupListResp
	(*BookListResp)(nil),                    // 8: book.BookListResp
	(*FileInfo)(nil),                        // 9: book.FileInfo
	(*Model)(nil),                           // 10: book.Model
	(*Group_Expand)(nil),                    // 11: book.Group.Expand
	nil,                                     // 12: book.Model.AdditionalInfoEntry
	(*Model_Toc)(nil),                       // 13: book.Model.Toc
	(*Model_Page)(nil),                      // 14: book.Model.Page
	(*Model_Page_RectAttr)(nil),             // 15: book.Model.Page.RectAttr
	(*Model_Page_AudioAttr)(nil),            // 16: book.Model.Page.AudioAttr
	(*Model_Page_AudioTimingAttr)(nil),      // 17: book.Model.Page.AudioTimingAttr
	(*Model_Page_HtmlAudioAttr)(nil),        // 18: book.Model.Page.HtmlAudioAttr
	(*Model_Page_RectAttr_Item)(nil),        // 19: book.Model.Page.RectAttr.Item
	(*Model_Page_RectAttr_Item_Rect)(nil),   // 20: book.Model.Page.RectAttr.Item.Rect
	(*Model_Page_AudioTimingAttr_SRT)(nil),  // 21: book.Model.Page.AudioTimingAttr.SRT
	(*Model_Page_HtmlAudioAttr_TagSRT)(nil), // 22: book.Model.Page.HtmlAudioAttr.TagSRT
}
var file_pb_model_proto_depIdxs = []int32{
	0,  // 0: book.Group.showType:type_name -> book.Group.ShowType
	11, // 1: book.Group.expand:type_name -> book.Group.Expand
	1,  // 2: book.RepoListResp.items:type_name -> book.Repo
	3,  // 3: book.GroupListResp.items:type_name -> book.Group
	2,  // 4: book.BookListResp.items:type_name -> book.Basic
	2,  // 5: book.Model.basicInfo:type_name -> book.Basic
	9,  // 6: book.Model.fileInfo:type_name -> book.FileInfo
	13, // 7: book.Model.toc:type_name -> book.Model.Toc
	14, // 8: book.Model.pages:type_name -> book.Model.Page
	12, // 9: book.Model.additionalInfo:type_name -> book.Model.AdditionalInfoEntry
	2,  // 10: book.Group.Expand.books:type_name -> book.Basic
	13, // 11: book.Model.Toc.children:type_name -> book.Model.Toc
	19, // 12: book.Model.Page.RectAttr.items:type_name -> book.Model.Page.RectAttr.Item
	21, // 13: book.Model.Page.AudioTimingAttr.timing:type_name -> book.Model.Page.AudioTimingAttr.SRT
	22, // 14: book.Model.Page.HtmlAudioAttr.timing:type_name -> book.Model.Page.HtmlAudioAttr.TagSRT
	20, // 15: book.Model.Page.RectAttr.Item.rect:type_name -> book.Model.Page.RectAttr.Item.Rect
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pb_model_proto_init() }
func file_pb_model_proto_init() {
	if File_pb_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_model_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Repo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Basic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RepoListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GroupListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*BookListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Model); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Group_Expand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*Model_Toc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*Model_Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Model_Page_RectAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*Model_Page_AudioAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*Model_Page_AudioTimingAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*Model_Page_HtmlAudioAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*Model_Page_RectAttr_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*Model_Page_RectAttr_Item_Rect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*Model_Page_AudioTimingAttr_SRT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_model_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*Model_Page_HtmlAudioAttr_TagSRT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_model_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_model_proto_goTypes,
		DependencyIndexes: file_pb_model_proto_depIdxs,
		EnumInfos:         file_pb_model_proto_enumTypes,
		MessageInfos:      file_pb_model_proto_msgTypes,
	}.Build()
	File_pb_model_proto = out.File
	file_pb_model_proto_rawDesc = nil
	file_pb_model_proto_goTypes = nil
	file_pb_model_proto_depIdxs = nil
}
